# Generated by Django 4.0.1 on 2022-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=111)),
                ('email', models.EmailField(blank=True, max_length=111)),
                ('attending', models.BooleanField(default=False)),
                ('dietary', models.TextField(blank=True, max_length=777)),
            ],
        ),
    ]
