# Generated by Django 4.0.1 on 2022-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary',
            field=models.CharField(blank=True, max_length=777),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='attending',
            field=models.BooleanField(default=None),
        ),
    ]
