# Generated by Django 4.0.1 on 2022-01-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_guest_dietary_alter_invitation_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='attending',
            field=models.BooleanField(),
        ),
    ]
