# Generated by Django 4.0.1 on 2022-01-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_invitation_attending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='dietary',
            new_name='food_allergies',
        ),
    ]
