# Generated by Django 4.0.1 on 2022-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_rename_dietary_guest_food_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('image', models.ImageField(null=True, upload_to='Media')),
                ('image_alt_text', models.CharField(max_length=111)),
                ('location', models.CharField(max_length=777)),
                ('detail', models.TextField(max_length=777)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='Media')),
                ('image1_alt_text', models.CharField(max_length=111)),
                ('p1_part1', models.TextField(max_length=1111)),
                ('p1_bold', models.CharField(max_length=222)),
                ('p1_part2', models.TextField(max_length=1111)),
                ('p2_part1', models.TextField(max_length=1111)),
                ('p2_bold', models.CharField(max_length=222)),
                ('p2_part2', models.TextField(max_length=1111)),
                ('image2', models.ImageField(null=True, upload_to='Media')),
                ('image2_alt_text', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Media')),
                ('image_alt_text', models.CharField(max_length=111)),
                ('first_name', models.CharField(max_length=222)),
                ('last_name', models.CharField(max_length=222)),
                ('role', models.CharField(max_length=222)),
                ('description', models.TextField(blank=True, max_length=222)),
            ],
        ),
    ]
