# Generated by Django 4.0.1 on 2022-01-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_accomodations_story_weddingparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zola_link', models.URLField(blank=True)),
                ('zola_data_registry_key', models.URLField(blank=True)),
                ('store_link', models.URLField(blank=True)),
                ('store_logo', models.ImageField(null=True, upload_to='Media')),
            ],
        ),
        migrations.RenameModel(
            old_name='Accomodations',
            new_name='Accomodation',
        ),
        migrations.RenameModel(
            old_name='Story',
            new_name='StoryText',
        ),
        migrations.RenameModel(
            old_name='WeddingParty',
            new_name='WeddingPartyMember',
        ),
    ]
