# Generated by Django 4.0.1 on 2022-01-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_registrylink_rename_accomodations_accomodation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrylink',
            old_name='zola_link',
            new_name='zolaLink',
        ),
    ]
