# Generated by Django 4.0.1 on 2022-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_galleryimage_remove_registrylink_store_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1111)),
                ('answer', models.TextField(max_length=1111)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('image_alt_text', models.CharField(max_length=111)),
                ('first_name', models.CharField(max_length=222)),
                ('last_name', models.CharField(max_length=222)),
                ('role', models.CharField(max_length=222)),
                ('description', models.TextField(blank=True, max_length=777)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=222)),
                ('detail', models.TextField(blank=True, max_length=1111)),
                ('departure_time', models.TextField(blank=True, max_length=1111)),
                ('venue_distance', models.CharField(blank=True, max_length=222)),
                ('downtown_distance', models.CharField(blank=True, max_length=222)),
            ],
        ),
        migrations.AddField(
            model_name='accomodation',
            name='block_name',
            field=models.CharField(blank=True, max_length=77),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='block_rate',
            field=models.CharField(blank=True, max_length=77),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='phone',
            field=models.CharField(blank=True, max_length=77),
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=777, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='detail',
            field=models.TextField(blank=True, max_length=777),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='location',
            field=models.CharField(blank=True, max_length=777),
        ),
    ]
