# Generated by Django 4.0.1 on 2022-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_faq_host_travel_accomodation_block_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytext',
            name='p1_story_owner',
            field=models.CharField(max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='storytext',
            name='p2_story_owner',
            field=models.CharField(max_length=222, null=True),
        ),
    ]
