# Generated by Django 4.0.1 on 2022-01-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_storytext_p1_story_owner_storytext_p2_story_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('songfile', models.FileField(upload_to='')),
                ('autoPlay', models.BooleanField()),
            ],
        ),
    ]
