# Generated by Django 4.0.1 on 2022-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='songfile',
            field=models.FileField(upload_to='audio'),
        ),
    ]
