# Generated by Django 4.0.1 on 2022-01-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_alter_audio_songfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
