# Generated by Django 4.0.1 on 2022-01-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='url',
            new_name='link',
        ),
    ]
