# Generated by Django 4.0.1 on 2022-01-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0015_rename_url_song_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture', models.TextField(max_length=1111)),
                ('source', models.TextField(max_length=1111)),
            ],
        ),
    ]
