# Generated by Django 4.0.1 on 2022-01-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0016_scripture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coming_Soon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_page', models.BooleanField(default=False)),
                ('story_page', models.BooleanField(default=False)),
                ('party_page', models.BooleanField(default=False)),
                ('registry_page', models.BooleanField(default=False)),
                ('rsvp_page', models.BooleanField(default=False)),
            ],
        ),
    ]
