# Generated by Django 4.0.1 on 2022-01-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0017_coming_soon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coming_Soon',
            new_name='ComingSoon',
        ),
    ]
