# Generated by Django 4.0.1 on 2022-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0018_rename_coming_soon_comingsoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='diet',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('vegan', 'vegan'), ('vegetarian', 'vegetarian')], default='none', max_length=10, null=True),
        ),
    ]
