# Generated by Django 4.0.1 on 2022-01-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0019_guest_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingPartyCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('image_alt_text', models.CharField(max_length=111)),
                ('caption', models.CharField(max_length=111)),
            ],
        ),
    ]
