# Generated by Django 4.0.1 on 2022-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0021_weddingpartymember_bridal_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('image_alt_text', models.CharField(max_length=111)),
                ('schedule_page', models.BooleanField(default=False)),
                ('registry_page', models.BooleanField(default=False)),
            ],
        ),
    ]
