# Generated by Django 4.0.1 on 2022-01-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0022_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='travel',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
