# Generated by Django 4.0.1 on 2022-01-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0023_travel_image_travel_image_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='faq_page',
            field=models.BooleanField(default=False),
        ),
    ]
