# Generated by Django 4.0.1 on 2022-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0024_bannerimage_faq_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='aso_ebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='hotel_accomodations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='extra_guests',
            field=models.IntegerField(null=True),
        ),
    ]
