# Generated by Django 4.0.1 on 2022-02-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0028_homeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='videodesktop',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='videomobile',
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image1desktop',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image1desktop_alt_text',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image1mobile',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image1mobile_alt_text',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image2desktop',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image2desktop_alt_text',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image2mobile',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image2mobile_alt_text',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image3desktop',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image3desktop_alt_text',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image3mobile',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='image3mobile_alt_text',
            field=models.CharField(blank=True, max_length=111),
        ),
    ]
