# Generated by Django 4.0.1 on 2022-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0029_remove_homeimage_videodesktop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='image1desktop_alt_text',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='image1mobile_alt_text',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
