# Generated by Django 4.0.2 on 2022-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0030_alter_homeimage_image1desktop_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_list', models.FileField(upload_to='')),
                ('invitation_list', models.FileField(upload_to='')),
            ],
        ),
    ]
