# Generated by Django 4.0.2 on 2022-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0031_massupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytext',
            name='video',
            field=models.FileField(null=True, upload_to='img'),
        ),
    ]
